### ISSUE TITLE
Post action body must be JSON

### ISSUE THREAD

**Issue by adriandieter** [benkehoe/sfn-callback-urls#6]
Post to callback url does not succeed due to `InvalidPostActionBody`. However the posted body is valid JSON and the Content-Type header is set to `application/json;charset=utf-8`.

It seems like the problem is a strict match of the Content-Type to `application/json`, which fails when the charset is specified in the Content-Type header.

Could this comparison be the problem?
https://github.com/benkehoe/sfn-callback-urls/blob/f82c6039c794094c3da0bd4e91935317a0a40ca6/src/sfn_callback_urls/post_actions.py#L49

## Example Post and log message:
Post to Callback:
`Content-Type: application/json;charset=utf-8`

```json
{
    "source": "foo",
    "id": "bar",
    "state": "success",
}
```

Log of ProcessCallbackFunction:

```json
{
    "timestamp": "2020-12-11T09:56:14.576580",
    "decode_time": 0.29622951199996805,
    "transaction_id": "xxx",
    "action": {
        "name": "post",
        "type": "post"
    },
    "error": {
        "type": "RequestError",
        "error": "InvalidPostActionBody",
        "message": "Post action body must be JSON"
    }
}
```

**Comment by benkehoe** [comment]
Thanks, I'll take care of this. Also a good time to update the Python runtime and dependencies.

**Comment by benkehoe** [comment]
This is fixed, both in the source and in the SAR app. Funnily enough, I was [already parsing this correctly for `Accept` headers](https://github.com/benkehoe/sfn-callback-urls/blob/20e47ecd0bc9ac7bb7758dc443e4d97fe26ac56e/src/sfn_callback_urls/callbacks.py#L174).

**Comment by adriandieter** [comment]
Cool, thank you! 🙌
